config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :results, only: [:new, :create, :index, :show]
  resources :appointments, only: [:new, :create, :index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :user
  belongs_to :test
  has_many :results, dependent: :destroy
  accepts_nested_attributes_for :results
end

app/models/metric.rb
class Metric < ApplicationRecord
  has_many :results, dependent: :destroy
  belongs_to :test
end

app/models/result.rb
class Result < ApplicationRecord
  belongs_to :metric
  belongs_to :appointment
end

app/models/test.rb
class Test < ApplicationRecord
  has_many :metrics, dependent: :destroy
  has_many :appointments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # has_many :users dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :appointments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  def new
    @appointment = Appointment.new
    @appointment.test = Test.find_by_name("Test sanguin")
    @appointment.test.metrics.each do |metric|
      @appointment.results << Result.new(metric: metric)
    end
  end

  def create
    # raise
    @appointment = Appointment.new(result_params)
    @appointment.user = current_user
    @appointment.test = Test.find_by_name("Test sanguin")
    if @appointment.save
      result_glycemie = params[:appointment][:results_attributes]["0"]
      Result.create!(appointment: @appointment, metric_id: result_glycemie[:metric_id], value: result_glycemie[:value].to_f)
      result_cholesterol = params[:appointment][:results_attributes]["1"]
      Result.create!(appointment: @appointment, metric_id: result_cholesterol[:metric_id], value: result_cholesterol[:value].to_f)
      result_transaminases = params[:appointment][:results_attributes]["2"]
      Result.create!(appointment: @appointment, metric_id: result_transaminases[:metric_id], value: result_transaminases[:value].to_f)
      result_creatinine_sanguine = params[:appointment][:results_attributes]["3"]
      Result.create!(appointment: @appointment, metric_id: result_creatinine_sanguine[:metric_id], value: result_creatinine_sanguine[:value].to_f)
      redirect_to appointment_path(@appointment)
    else
      render "new"
    end
  end

  def index
    @appointments = Appointment.all.order('datetime DESC')
  end

  def show
    @appointment = Appointment.find(params[:id])
    results = @appointment.results
    @glycemie_check = metrics_check(results[0])
    @cholesterol_check = metrics_check(results[1])
    @transaminases_check = metrics_check(results[2])
    @creatinine_check = metrics_check(results[3])
  end

  private

  def metrics_check(result)
    case result.metric.name
    when "Glycémie"
      result.value > 1.1 ? 'arrow-down' : 'check'
    when "Cholestérol"
      result.value > 2 ? 'arrow-up' : 'check'
    when "Transaminases"
      result.value > 50 ? 'arrow-down' : 'check'
    when "Créatinine sanguine"
      result.value > 110 ? 'arrow-up' : 'check'
    end
  end

  def result_params
    params.require(:appointment).permit(:datetime, :results_attributes)
    #result_attributes: [:metric_id, :value]
  end

  def sort_by_date(dates, direction="ASC")
    sorted = dates.sort
    sorted.reverse! if direction == "DESC"
    sorted
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]
  layout "home", only: [ :home ]
  def home
  end
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController

  def index
    @results = Result.all
  end


  def show
    @result = Result.find(params[:id])
  end

  def new
    @result = Result.new
  end

  def create
    @result = Result.new(result_params)
    @result.save
    #rajouter conditions si ça ne réussit pas
    redirect_to result_path(@result)
  end

  private

  def result_params
    params.require(:result).permit(:metric_id, :appointment_id, :value)
  end
end

app/controllers/test_controller.rb
class TestController < ApplicationController

  def show
    @test = Test.find(params[:id])
  end

  def new
    @test = Test.new
  end

  def create
    @test = Test.new(test_params)
    @test.save
    #rajouter conditions si ça ne réussit pas
    redirect_to test_path(@test)
  end

  def index
    tests = Test.all
  end

  private

  def result_params
    params.require(:test).permit(:name, :description, :value)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/appointments/index.html.erb
<div class="header__image">
  <div class="header-opacity">
    <div class="header__title v-center">
      <h1>Mes Résultats</h1>
    </div>
  </div>
</div>

<div class="appointments-container">
  <div class="col">
    <% @appointments.each do |appointment| %>
      <div class="card">
        <div class="card-body">
          <div class="card-logo-title">
            <i class="fas fa-tint"></i>
            <div class="card-title"><h3><%= appointment.test.name %></h3></div>
          </div>
          <div class="card-date-detail">
            <p class="card-subtitle"><%= appointment.datetime.strftime("%d/%m/%Y") %></p>
            <%= link_to "Détails", appointment_path(appointment), class: "btn btn-outline-warning mt-4" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/appointments/new.html.erb
<div class="header__image">
  <div class="header-opacity">
    <div class="header__title v-center">
      <h1>Entrez vos résultats</h1>
    </div>
  </div>
</div>

<div class="col appointment-form-container">
  <div class="card" style=" margin-top: 20px; padding-bottom: 20px">
    <%= simple_form_for @appointment do |f| %>
      <div class="card-body">
        <div class="row">
          <div class="col sm-12 create">
            <label for="example">Date & heure du test</label>
            <input type="datetime-local" id="meeting-time" name="appointment[datetime]" 
            value="2020-09-04T00:00" min="2000-01-02T00:00" max="2025-06-14T00:00" class="form-group form-control">
            <%= f.simple_fields_for :results do |ff| %>
              <%= ff.object.metric.name %>
              <%= ff.input :metric_id, as: :hidden, input_html: {class: "date"} %>
              <%= ff.input :value, label: false, placeholder: "Entrez ici votre taux en #{ff.object.metric.unit}" %>
            <% end %>
            <%= f.submit "confirmer", class: "btn btn-warning" %> 
          </div>
        </div>
      </div>
      
    <% end %>
    
  </div>
</div>

app/views/appointments/show.html.erb
<div class="header__image">
  <div class="header-opacity">
    <div class="header__title">
      <h1><%= @appointment.test.name %></h1>
      <h5><%= @appointment.datetime.strftime("%d/%m/%Y") %></h5>
    </div>
  </div>
</div>

<div class="appointment-results-container">
  <div class="col">
    <div class="card">
      <div class="card-body">
        <div class="row">
          <div class="col">
            <h4 class="card-title">Nos recommandations</h4>
            <div class="row">
              <div class="result-recomandation">
                <div class="bloc-result"><div class="card-subtitle">Pratique sportive</div><div class="log1"><%= icon('fas', @cholesterol_check) %></div></div>
                <div class="bloc-result"><div class="card-subtitle">Consommation de sucre</div><div class="log2"><%= icon('fas', @glycemie_check) %></div></div>
                <div class="bloc-result"><div class="card-subtitle">Consommation d'eau</div><div class="log3"><%= icon('fas', @creatinine_check) %></div></div>
                <div class="bloc-result"><div class="card-subtitle">Gain / Perte de poids</div><div class="log4"><%= icon('fas', @transaminases_check) %></div></div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <% @appointment.results.each do |result| %>
    <div class="col">
      <div class="card">
        <div class="card-body">
          <div class="row">
            <div class="col">
              <h4 class="card-title"><%= result.metric.name %></h4>
              <div class="taux">
                <p class="data-hemo"><%= result.value %></p>
                <p class="type-hemo"><%= result.metric.unit %></p>
              </div>
              <div id="<%= result.metric.name %>" data-taux="<%= result.value.to_json %>"></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Izia</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>

    <script src="https://cdn.anychart.com/releases/8.9.0/js/anychart-base.min.js" type="text/javascript"></script>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Izia</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body class="background">
    <div class="background-opacity">
        <%= render 'shared/navbar' %>
        <%= render 'shared/flashes' %>
        <%= yield %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<div class="logo-home">
  <div class="img-logo"></div>
  <div class="logo"><h1>IZIA</h1></div>
</div>

<div>
  <div class="slogan">
    <h1 class="title">Maîtrisez vos analyses médicales</h1>
  </div>

  <div class="begin">

    <% if @user = true %>
    <%= link_to "Entrez vos données", new_appointment_path, class: "btn btn-light" %>
    <% else  %>
    <%= link_to "Entrez vos données", user_session_path, class: "btn btn-light" %>
    <% end %>
  </div>

</div>

app/views/results/index.html.erb
<div class="header__image">
  <div class="header-opacity">
    <div class="header__title">
      <h1>més résultats</h1>
    </div>
  </div>
</div>


<div>
  <% @results.each do |result| %>
    <div class="col">
        <div class="card">
            <div class="card-body">
              <div class="row">
                <div class="col">
                  <h5 class="card-title"><%= result.appointment.test.name %></h5>
                </div>
                <div class="col">
                  <h6 class="card-subtitle mb-2 text-muted"><%= result.appointment.datetime %></h6>
                </div>
              </div>
              <p class="card-text"><%= result.appointment.test.description %></p>
              <%= link_to "En savoir plus", result_path(result), class: "card-link" %>
            </div>
      </div>
    </div>
  <% end %>
</div>

app/views/results/new.html.erb
<!-- <div class="header__image">
  <div class="header-opacity">
    <div class="header__title">
      <h1>Entrez vos résultats</h1>
    </div>
  </div>
</div>

<%= simple_form_for(@result) do |f| %>


  <%= f.input :value %>

  <%= f.label :metric_id %>
  <%= f.text_field :value %>

  <%= f.label :metric_id %>
  <%= f.text_field :value %>

  <%= f.submit %>
<% end %>
-->

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand fixed-bottom navbar-light navbar-bottom">
  <%= link_to "#", class: "navbar-brand" do %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>



  <div class="collapse navbar-collapse navbar-bottom-style" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <div class="navbar-background-logo graph-logo">
          <%= link_to icon('fas', 'chart-bar'), appointments_path, class: "nav-link color-logo"  %>
          </div>        
        </li>
        <li class="nav-item">
        <div class="navbar-background-logo">
          <%= link_to icon('fas', 'plus'), new_appointment_path, class: "nav-link color-logo"  %>
        </div> 
        </li>
        <li class="nav-item">
        <div class="navbar-background-logo">
          <%= link_to icon('fas', 'sign-out-alt'), destroy_user_session_path, method: :delete, class: "nav-link color-logo"  %>
        </div> 
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to icon('fas', 'sign-in-alt', 'Login'), new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>